version: '3'

volumes:
  # We'll define a volume that will store the data from the postgres databases:
  cms-data:
    driver: local

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    restart: always
    volumes:
      - cms-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ukefdbu
      - POSTGRES_PASSWORD=secured-password
      - POSTGRES_DB=ukefcms
